### ISSUE TITLE
MeshEffect doesn't work with Layout system

### ISSUE THREAD

**Issue by markv12** [mob-sakai/MeshEffectForTextMeshPro#6]
I am using this library for the Outline 8 shadow effect on a TextMesh Pro Text object. The resulting shadow is sharper and looks better on pixel fonts than the default TextMesh Pro outline.

But I'm finding that it doesn't work well with the Unity layout system. 
If TextMesh Pro text objects are part of a layout or have a ContentSizeFitter on them, At certain times, especially if you call:
`LayoutRebuilder.ForceRebuildLayoutImmediate(GetComponent<RectTransform>());`
You get an error like this:

`Mesh.vertices is too small. The supplied vertex array has less vertices than are referenced by the triangles array.
UnityEngine.Mesh:set_vertices(Vector3[])
TMPro.TextMeshPro:GenerateTextMesh() (at Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TMPro_Private.cs:3796)
TMPro.TextMeshPro:CalculateLayoutInputVertical() (at Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TextMeshPro.cs:534)
UnityEngine.Canvas:SendWillRenderCanvases()`

Any idea what might be causing this?

Thank you!

**Comment by mob-sakai** [comment]
Hi @markv12 
Thank you for reporting!

**Comment by markv12** [comment]
I also seem to get similar errors when adding the Shadow effect for the first time. 
The errors usually come in sets, one error for Verts, UVs, Tris, etc...
It seems like there is some event that isn't being listened for. Text mesh pro tries to update the verts and because the other lists have 9x more elements than they would usually, you get this error.

**Comment by mob-sakai** [comment]
Yes.
To be honest, in some cases, UIShadow doesn't work well with TMPro. :(

I fixed some of this plugin.
If it works for you, I will release it ASAP. :)
[fixed.unitypackage.zip](https://github.com/mob-sakai/MeshEffectForTextMeshPro/files/3069121/fixed.unitypackage.zip)

**Comment by markv12** [comment]
The relevant changes are in BaseMeshEffect.cs only correct?
Or are there other changes that are important to the fix? 
I'm still getting the error when using a ContentSizeFitter.

If a TextMesh Pro object on a canvas has a ContentSizeFitter and I do anything like add another UI object to the canvas, I get this error and several others for UVs, Colors, etc...

`Mesh.vertices is too small. The supplied vertex array has less vertices than are referenced by the triangles array.
UnityEngine.Mesh:set_vertices(Vector3[])
TMPro.TextMeshPro:GenerateTextMesh() (at Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TMPro_Private.cs:3796)
TMPro.TextMeshPro:CalculateLayoutInputVertical() (at Library/PackageCache/com.unity.textmeshpro@1.3.0/Scripts/Runtime/TextMeshPro.cs:534)
UnityEngine.Canvas:SendWillRenderCanvases()`
